### ISSUE TITLE
Bug in the passthrough?

### ISSUE THREAD

**Issue by FreeMasen** [cosock/cosock#21]
The return value from [blocked discarded](https://github.com/cosock/cosock/blob/324186f8682f85f3d417896efa8da0be4c5593a3/cosock/socket/internals.lua#L33), is this intentional?

**Comment by azdle** [comment]
What's discarded? The values returned from `transform.blocked` are the input values to the next call to `inner_sock[method]` when the coroutine loops around again.

**Comment by FreeMasen** [comment]
`inputparameters` is defined [here](https://github.com/cosock/cosock/blob/324186f8682f85f3d417896efa8da0be4c5593a3/cosock/socket/internals.lua#L19). so re-assigning [here](https://github.com/cosock/cosock/blob/324186f8682f85f3d417896efa8da0be4c5593a3/cosock/socket/internals.lua#L33) would end up being discarded.

**Comment by FreeMasen** [comment]
Ohhh! I somehow missed the infinite loop there...
